import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Clock3,WalletCards,Coffee}from'lucide-react';
import{supabase}from'../../supabase';
import{formatCurrency}from'../utils/storage';
import{diaEspecial,proximosDiasEspeciais,diasEntre,resumoExtras,valorFeriadoTrabalhado,valorHoraExtra}from'../../lib/feriados';
import{PontoJornada,PontoRegistro,analisarDia,fmtHM,hhmm,hojeStr,inicioDaSemana,jornadaDoDia,minutosPrevistos,somarDias}from'../../lib/pontoCalc';

export const MeuPontoView:React.FC<{colaboradorId:string;nome:string;salarioBase?:number}>=({colaboradorId,nome,salarioBase=0})=>{
 const[func,setFunc]=useState<any>(null),[jornadas,setJornadas]=useState<PontoJornada[]>([]),[registros,setRegistros]=useState<PontoRegistro[]>([]),[banco,setBanco]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const hoje=hojeStr();
 useEffect(()=>{let ok=true;(async()=>{const{data:f}=await supabase.from('ponto_funcionarios').select('id,numero_relogio,tolerancia_minutos').eq('colaborador_id',colaboradorId).eq('ativo',true).maybeSingle();if(!f){if(ok){setLoading(false);setFunc(null)}return}const ini=somarDias(hoje,-45);const[j,r,b]=await Promise.all([supabase.from('ponto_jornadas').select('*').eq('funcionario_id',f.id),supabase.from('ponto_registros').select('*').eq('funcionario_id',f.id).gte('data',ini).order('data',{ascending:false}),supabase.from('ponto_banco_horas').select('minutos,tipo,validade').eq('funcionario_id',f.id)]);if(ok){setFunc(f);setJornadas(j.data||[]);setRegistros(r.data||[]);setBanco(b.data||[]);setLoading(false)}})();return()=>{ok=false}},[colaboradorId,hoje]);
 const map=useMemo(()=>new Map(registros.map(r=>[r.data,r])),[registros]),jornada=jornadaDoDia(jornadas,hoje),reg=map.get(hoje)||null;
 const a=analisarDia(reg,jornada,hoje,hoje,func?.tolerancia_minutos??10,new Date().getHours()*60+new Date().getMinutes());
 const ini=inicioDaSemana(hoje),dias=useMemo(()=>Array.from({length:7},(_,i)=>somarDias(ini,i)),[ini]);
 const semana=dias.map(data=>{const r=map.get(data)||null,j=jornadaDoDia(jornadas,data),a=analisarDia(r,j,data,hoje,func?.tolerancia_minutos??10);return{data,r,j,a}});
 const saldo=banco.filter(m=>m.minutos<0||!m.validade||m.validade>=hoje).reduce((s,m)=>s+m.minutos,0);
 const horas=semana.reduce((s,d)=>s+d.a.trabalhados,0),prev=semana.reduce((s,d)=>s+minutosPrevistos(d.j),0);
 const esp=diaEspecial(hoje),proximos=proximosDiasEspeciais(hoje,5),extras=resumoExtras(semana.map(d=>({data:d.data,trabalhados:d.a.trabalhados,previstos:d.a.previstos,extra:d.a.extra})),salarioBase,func?.tolerancia_minutos??10);
 const statusBase={presente:'Presente',atrasado:'Atrasado',incompleto:'Incompleto',ausente:'Ausente',folga:'Folga',aguardando:'Aguardando'}[a.status];
 const status=esp&&a.trabalhados===0&&!reg?.entrada?(esp.tipo==='feriado'?'Feriado':'Facultativo'):statusBase;
 const card='bg-[var(--bg-card)] border border-[var(--border-color)] rounded-2xl p-4 shadow-sm';
 if(loading)return <div className="p-8 text-center text-sm text-[var(--text-muted)]">Carregando Meu Ponto...</div>;
 if(!func)return <div className={card}><h2 className="text-lg font-black">Meu Ponto</h2><p className="text-sm text-[var(--text-muted)] mt-2">Seu cadastro ainda não está vinculado ao ponto eletrônico.</p></div>;
 return <div className="space-y-5"><div><h2 className="text-2xl font-black">Meu Ponto</h2><p className="text-sm text-[var(--text-muted)] mt-1">{nome} · acompanhamento individual</p></div>
 {esp&&<div className={'rounded-2xl border p-4 text-sm '+(esp.tipo==='feriado'?'bg-amber-500/10 border-amber-500/30 text-amber-200':'bg-sky-500/10 border-sky-500/30 text-sky-200')}><b>{esp.tipo==='feriado'?'Hoje é feriado':'Hoje é ponto facultativo'}: {esp.nome}.</b> {esp.tipo==='feriado'?('Se trabalhar hoje, o dia é pago em dobro (2× a diária'+(salarioBase>0?' = '+formatCurrency(valorFeriadoTrabalhado(salarioBase)):'')+').'):'Ponto facultativo não dobra o dia; combine com a empresa se haverá expediente.'}</div>}
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div className={card}><Clock3 className="w-5 h-5 mb-3 text-[var(--accent-red)]"/><b className="text-2xl">{fmtHM(a.trabalhados)}</b><p className="text-xs text-[var(--text-muted)]">Hoje</p></div><div className={card}><CalendarDays className="w-5 h-5 mb-3 text-[var(--accent-red)]"/><b className="text-2xl">{fmtHM(horas)}</b><p className="text-xs text-[var(--text-muted)]">Semana · meta {fmtHM(prev)}</p></div><div className={card}><WalletCards className="w-5 h-5 mb-3 text-[var(--accent-red)]"/><b className="text-2xl">{saldo>=0?'+':'-'}{fmtHM(Math.abs(saldo))}</b><p className="text-xs text-[var(--text-muted)]">Banco de horas</p></div><div className={card}><Coffee className="w-5 h-5 mb-3 text-[var(--accent-red)]"/><b className="text-xl">{status}</b><p className="text-xs text-[var(--text-muted)]">Status de hoje</p></div></div>
 <div className={card}><h3 className="font-black mb-4">Registro de hoje</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['Entrada',reg?.entrada],['Início intervalo',reg?.inicio_intervalo],['Fim intervalo',reg?.fim_intervalo],['Saída',reg?.saida]].map(([l,v])=><div key={l as string} className="rounded-xl bg-[var(--bg-main)] border border-[var(--border-color)] p-3"><small className="text-[10px] uppercase font-bold text-[var(--text-muted)]">{l}</small><p className="text-lg font-black mt-1">{hhmm(v as string|null)}</p></div>)}</div></div>
 <div className={card}><h3 className="font-black mb-4">Jornada atual</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm"><div>Entrada<b className="block mt-1">{hhmm(jornada?.entrada)}</b></div><div>Intervalo<b className="block mt-1">{hhmm(jornada?.inicio_intervalo)} — {hhmm(jornada?.fim_intervalo)}</b></div><div>Saída<b className="block mt-1">{hhmm(jornada?.saida)}</b></div><div>Carga prevista<b className="block mt-1">{fmtHM(minutosPrevistos(jornada))}</b></div></div></div>
 <div className={card}><h3 className="font-black mb-4">Semana atual</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-[var(--text-muted)] border-b border-[var(--border-color)]"><th className="pb-2">Dia</th><th>Entrada</th><th>Intervalo</th><th>Saída</th><th>Horas</th><th>Status</th></tr></thead><tbody>{semana.map(d=><tr key={d.data} className="border-b border-[var(--border-color)] last:border-0"><td className="py-2 font-bold">{new Date(d.data+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}</td><td>{hhmm(d.r?.entrada)}</td><td>{hhmm(d.r?.inicio_intervalo)} — {hhmm(d.r?.fim_intervalo)}</td><td>{hhmm(d.r?.saida)}</td><td className="font-bold">{fmtHM(d.a.trabalhados)}</td><td>{(()=>{const e=diaEspecial(d.data);if(!e)return d.a.status;return d.a.trabalhados===0?(e.tipo==='feriado'?'Feriado':'Facultativo')+' · '+e.nome:d.a.status+' · '+(e.tipo==='feriado'?'feriado em dobro':'facultativo')})()}</td></tr>)}</tbody></table></div></div>
 <div className={card}><h3 className="font-black mb-4">Próximos feriados e pontos facultativos</h3><ul className="space-y-2 text-sm">{proximos.map(f=>{const n=diasEntre(hoje,f.data);return <li key={f.data} className="flex items-center justify-between gap-3 border-b border-[var(--border-color)] last:border-0 pb-2 last:pb-0"><span><b>{new Date(f.data+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'})}</b> · {f.nome}</span><span className="flex items-center gap-2 shrink-0"><small className={'text-[10px] font-black uppercase px-2 py-0.5 rounded-full border '+(f.tipo==='feriado'?'border-amber-500/30 text-amber-300':'border-sky-500/30 text-sky-300')}>{f.tipo==='feriado'?'Feriado':'Facultativo'}</small><small className="text-[var(--text-muted)]">{n===1?'amanhã':'em '+n+' dias'}</small></span></li>})}</ul><p className="text-xs text-[var(--text-muted)] mt-4">Feriado trabalhado = 2× a diária{salarioBase>0?' ('+formatCurrency(valorFeriadoTrabalhado(salarioBase))+')':''} · Hora extra = valor da hora × 1,5{salarioBase>0?' ('+formatCurrency(valorHoraExtra(salarioBase))+'/h)':''}</p></div>
 {salarioBase>0&&(extras.feriadosTrabalhados>0||extras.minutosExtra>0)&&<div className={card}><h3 className="font-black mb-4">Adicionais da semana</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span>Feriado trabalhado ({extras.feriadosTrabalhados}×)</span><b>{formatCurrency(extras.valorFeriados)}</b></div><div className="flex justify-between"><span>Hora extra ({fmtHM(extras.minutosExtra)})</span><b>{formatCurrency(extras.valorExtras)}</b></div></div></div>}
 </div>
};